config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#welcome"
  require "sidekiq/web"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  namespace :users do
    root to: "basket_items#index"
  end

  patch 'baskets/:id/toggle_items', to: 'baskets#toggle_items', as: "toggle_items"
  resources :baskets
  resources :basket_items
end

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_baskets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items, dependent: :destroy
  # after_commit -> (basket) { broadcast_replace_to basket }
  after_update -> (basket) { basket.broadcast_replace_to basket }
  after_destroy -> (basket) { basket.broadcast_remove_to basket }


  accepts_nested_attributes_for :basket_items

  def image_name
    "shopping-venture.png"
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_basket, only: %i[ show update edit destroy toggle_items]

  # GET /baskets
  def index
    records= policy_scope(Basket).includes(:basket_items)
    @pagy, @baskets = pagy(records, items: 6)
  end

  # GET /baskets/:id
  def show
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # POST /baskets/create
  def create
    @basket = Basket.new(basket_params.merge(user_id: current_user.id))

    if @basket.save
      respond_to do |format|
        format.html { redirect_to baskets_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /baskets/:id/edit
  def edit
  end

  def toggle_items
    status = params[:status]
    if BasketItem.get_statuses.include?(status)
      toggled_basket_items = @basket.basket_items.each { |bi| bi.status = status }
      respond_to do |format|
        ActiveRecord::Base.transaction do
          if @basket.update(basket_items: toggled_basket_items)
            format.html { redirect_to basket_url(@basket), notice: "Basket items updated" }
            format.turbo_stream {
              render turbo_stream: turbo_stream.replace("basket_#{@basket.id}", render_to_string(partial: 'basket', locals: { basket: @basket }))
            }
          else
            format.html { render :edit, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PUT /basket/:id
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to basket_url(@basket), notice: "basket was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket/:id
  def destroy
    @basket.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("basket_#{@basket.id}")}
    end
  end

  private
    def basket_params
      params.require(:basket).permit(:name)
    end

    def set_basket
      @basket = policy_scope(Basket).find(params[:id])
    end
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/views/baskets/_basket.html.erb
<%= turbo_frame_tag basket do %>
  <div class="p-1 m-1 w-96 bg-white-200 rounded overflow-hidden shadow-lg shadow-slate-300 border-2 border-slate-100 hover:shadow-lime-100 hover:border-1 hover:border-lime-100">
    <div class="grid grid-cols-2 divide-x-2 divide-gray-100">
      <%= image_tag(basket.image_name, class: "block object-contain h-32 box-border") %>
        <%= link_to basket_items_path(basket_id: basket.id), data: { turbo_frame: "_top" } do %>
          <div class="pl-2 box-border">
            <p class="text-center text-2xl border-b-2 border-gray-100">
              <strong> <%= basket.name %> </strong>
            </p>
            <div class="flex justify-between mt-1">
              <span>Total Item</span>
              <span><%= basket.basket_items.size %></span>
            </div>
            <div class="flex justify-between mt-1">
              <span>Retrieved Item</span>
              <span><%= basket.basket_items.select { |bi| !bi.pending? }.size %></span>
            </div>
            <div class="flex justify-between mt-1">
              <span>Pending Item</span>
              <span><%= basket.basket_items.select { |bi| bi.pending? }.size %></span>
            </div>
          </div>
        <% end %>
    </div>
    <div class="grid grid-cols-2">
      <%= button_to "Edit", edit_basket_path(basket), method: :get, data: { turbo_frame: "edit_basket" }, class: "w-full btn bg-red-100 mr-2 px-2" %>
      <%= button_to "Reset All", toggle_items_path(basket, status: BasketItem::Statuses::PENDING ), method: :patch, data: { turbo_frame: dom_id(basket)}, type: "button", class: "w-full btn bg-cyan-100 mr-2 px-2" %>
    </div>
      <%= button_to "Pickup All", toggle_items_path(basket, status: BasketItem::Statuses::PICKED_UP), method: :patch, data: { turbo_frame: dom_id(basket)}, type: "button", class: "w-full btn bg-red-100 mr-2 px-2" %>
  </div>
<% end %>

app/views/baskets/_form.html.erb
<%= form_with(model: basket, id: "basket_form", class: "bg-pink-100") do |form| %>
  <% if basket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(basket.errors.count, "error") %> prohibited this basket from being saved:</h2>
      <ul>
        <% basket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bg-slate-100 max-w-xl p-1 m-1 bg-white-200 rounded overflow-hidden shadow-lg shadow-slate-300 border-2 border-slate-200 hover:shadow-lime-100 hover:border-1 hover:border-slate-400">
    <%= image_tag(basket.image_name, class: "block object-contain h-32 box-border mb-2") %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  <div class="grid grid-cols-2 gap-2">
    <%= form.submit "Create", class: "btn bg-cyan-100", data: { modal_target: "submitButton" } %>
  </div>
<% end %>

app/views/baskets/create.turbo_stream.erb
<%= turbo_stream.append "baskets", @basket %>
<%= turbo_stream.update "new_basket", "" %>

app/views/baskets/edit.html.erb
<main>
  <%= turbo_frame_tag "edit_basket" do %>
      <div data-modal-target="modal" data-controller="modal" class="flex items-center justify-center fixed z-40 inset-0 h-full p-6 backdrop-blur-md">
      <div data-action="keyup@document->modal#escClose click@window->modal#outsideClick">
        <%= render "form", basket: @basket  %>
      </div>
    </div>
  <% end %>
</main>

app/views/baskets/index.html.erb
<%= link_to "Add New", new_basket_path, data: { turbo_frame: "new_basket" }, type: "button", class: "w-full btn bg-purple-100 mr-2 px-2" %>

<div class="m-auto max-w-7xl flex flex-wrap justify-center" id="baskets">
    <% @baskets.each do |basket| %>
      <%= turbo_stream_from basket %>
      <%= render basket %>
    <% end %>
</div>

<%== pagy_nav(@pagy) %>

<%= turbo_frame_tag "new_basket" %>
<%= turbo_frame_tag "edit_basket" %>

app/views/baskets/new.html.erb
<main>
  <%= turbo_frame_tag "new_basket" do %>
      <div data-modal-target="modal" data-controller="modal" class="flex items-center justify-center fixed z-40 inset-0 h-full p-6 backdrop-blur-md">
      <div data-action="keyup@document->modal#escClose click@window->modal#outsideClick">
        <%= render "form",basket: @basket  %>
      </div>
    </div>
  <% end %>
</main>

app/views/baskets/show.html.erb
<%= turbo_stream_from @basket %>
<%= render @basket %>
<div>
  <%= link_to "Edit this basket", edit_basket_path(@basket) %> |
  <%= link_to "Back to baskets", baskets_path %>

  <%= button_to "Destroy this basket", @basket,  data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
</div>

app/views/baskets/toggle_items.turbo_stream.erb
<%= turbo_stream.replace @basket, partial: "basket", locals: { basket: @basket } %>

app/views/baskets/update.turbo_stream.erb
<%= turbo_stream.replace "basket", @basket %>