config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#welcome"
  require "sidekiq/web"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  namespace :users do
    root to: "basket_items#index"
  end

  patch 'baskets/:id/toggle_items', to: 'baskets#toggle_items', as: "toggle_items"
  resources :baskets
  resources :basket_items
end

app/views/layouts/shared/_sign_in.html.erb
<%= turbo_frame_tag "sign_in_up_modal" do %>
  <dialog data-controller="dialog" data-dialog-target="dialog">
    <main data-action="click@window->dialog#outsideClick" data-dialog-target="modalBox">
      <%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "w-full"%>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "current-password", class: "w-full" %>
        </div>

        <div class="grid grid-cols-3 gap-1 p-2">
          <%= link_to "Home", root_path, data: { turbo_frame: "_top" }, class: "btn w-full bg-cyan-100" %>
          <%= link_to "Sign up", new_user_registration_path, data: { turbo_frame: "sign_up_modal" }, class: "btn w-full bg-red-100" %>
          <%= f.submit "Log in", class: "btn w-full bg-lime-100", data: { turbo: false } %>
        </div>
      <% end %>
    </main>
  </dialog>
<% end %>

app/views/layouts/shared/_sign_up.html.erb
<%= turbo_frame_tag "sign_in_up_modal" do %>
  <dialog data-controller="dialog" data-dialog-target="dialog">
    <main data-action="click@window->dialog#outsideClick" data-dialog-target="modalBox">
      <%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
        <div class="field">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, class: "w-full" %>
        </div>

        <div class="field">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, class: "w-full" %>
        </div>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "w-full"%>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "current-password", class: "w-full" %>
        </div>

        <div class="grid grid-cols-3 gap-1 p-2">
          <%= link_to "Home", root_path, data: { turbo_frame: "_top" }, class: "btn w-full bg-cyan-100" %>
          <%= link_to "Log In", new_user_session_path, data: { turbo_frame: "sign_in_up_modal" }, class: "btn w-full bg-red-100" %>
          <%= f.submit "Sign In ", class: "btn w-full bg-lime-100", data: { turbo: false } %>
        </div>
      <% end %>
    </main>
  </dialog>
<% end %>