config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#welcome"
  require "sidekiq/web"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  namespace :users do
    root to: "basket_items#index"
  end

  patch 'baskets/:id/toggle_items', to: 'baskets#toggle_items', as: "toggle_items"
  resources :baskets
  resources :basket_items
end

app/models/basket_item.rb
# == Schema Information
#
# Table name: basket_items
#
#  id         :bigint           not null, primary key
#  measure    :string           default(""), not null
#  name       :string           not null
#  note       :string
#  quantity   :float            default(1.0), not null
#  status     :string           default("pending"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  basket_id  :bigint           not null
#
# Indexes
#
#  index_basket_items_on_basket_id  (basket_id)
#
# Foreign Keys
#
#  fk_rails_...  (basket_id => baskets.id)
#
class BasketItem < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :name_note_search,
                  against: %i(name note),
                  using: {
                    tsearch: {
                      prefix: true,
                    }
                  }

  belongs_to :basket

  module Statuses
    PENDING = 'pending'
    PICKED_UP = 'picked_up'
  end

  class << self
    def get_statuses
      Statuses.constants(false).map { |c| Statuses.const_get(c) }
    end
  end

  validates :status, inclusion: { in: self.get_statuses }
  validates :name, uniqueness: { scope: :basket_id }
  after_validation -> (item) { name.strip! }


  def image_name
    "shopping-venture.png"
  end

  def qty_measure_to_words
    if measure.present?
      "#{self.quantity} x #{self.measure}"
    else
      "#{self.quantity}"
    end
  end

  def pending?
    self.status == Statuses::PENDING
  end

  def toggled_status
    if self.pending?
     Statuses::PICKED_UP
    else
      Statuses::PENDING
    end
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_basket_item, only: %i[ show edit update destroy ]

  # GET /basket_items
  def index
    records = policy_scope(BasketItem).order([status: :asc, name: :asc])
    records = records.name_note_search(params[:query]) if params[:query].present?
    records = records.where({ basket_items: { basket_id: params[:basket_id] } }) if params[:basket_id].present?

    @search_basket = params[:basket_id]
    @search_value =  params[:query]
    @pagy, @basket_items = pagy(records, items: 20, link_extra: 'data-turbo-frame="basket_items"')
    @basket_item = BasketItem.new
    @baskets = policy_scope(Basket)

    respond_to do |format|
      format.html { render :index }
      format.turbo_stream
    end
  end

  # GET basket_items/:id
  def show
  end

  # GET basket_items/new
  def new
    @baskets = policy_scope(Basket)
    @basket_item = BasketItem.new
  end

  # POST basket_items
  def create
    @basket_item = BasketItem.new(basket_item_params)

    respond_to do |format|
      if @basket_item.save
        format.turbo_stream
        format.html { redirect_to basket_items_url, notice: "Basket item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # GET /basket_items/:id/edit
  def edit
    @baskets = policy_scope(Basket)
  end

  # PATCH/PUT /basket_items/:id
  def update
    respond_to do |format|
      if @basket_item.update(basket_item_params)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace("basket_item_#{@basket_item.id}", render_to_string(partial: 'basket_item', locals: { basket_item: @basket_item }))
        }
        #format.html { redirect_to basket_item_path(@basket_item), notice: "Basket item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/:id
  def destroy
    @basket_item.destroy

    respond_to do |format|
      format.html { redirect_to basket_items_url, notice: "Basket item was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("basket_item_#{@basket_item.id}")}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket_item
      @basket_item = policy_scope(BasketItem).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def basket_item_params
      params.require(:basket_item).permit(:basket_id, :item_id, :name, :note, :quantity, :measure, :status)
    end
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/views/basket_items/_basket_item.html.erb
<%= turbo_frame_tag basket_item do %>
  <main class="my-3 grid grid-cols-2 grid-rows-2 gap-1 shadow-slate-300 shadow-lg border-2 border-slate-100 hover:shadow-lime-100 hover:border-1, hover:border-lime-100">
    <div class="border-b-2 border-slate-100">
      <h3 class="m-auto text-center">
        <%= basket_item.name %>
      </h3>
    </div>

    <div class="grid grid-cols-2 mt-0">
      <%= button_to "Edit", edit_basket_item_path(basket_item), method: :get, data: { turbo_frame: "edit_basket_item" }, class: "w-full btn m-0 ring-1 ring-cyan-100 hover:bg-cyan-100" %>
      <%= button_to "#{basket_item.pending? ?  "Done" : "Undo"}", basket_item_path(basket_item, basket_item: { status: basket_item.toggled_status }), method: :patch, class: "m-0 w-full btn  #{basket_item.pending? ? "bg-lime-100" : "bg-cyan-100" }", data: { turbo_frame: dom_id(basket_item) } %>
    </div>

    <div class="flex justify-between">
      <span class="mx-2">
        <small>
          <%= basket_item.qty_measure_to_words %>
        </small>
      </span>
      <span class="mx-2">
        <small>
          <%= basket_item.basket&.name %>
        </small>
      </span>
    </div>

    <div class="flex justify-end">
      <span class="mx-2">
        <small>
          <%= basket_item.updated_at.strftime("%b-%d %H:%M") %>
        </small>
      </span>
    </div>
  </main>
<% end %>

app/views/basket_items/_form.html.erb
<%= form_with(model: basket_item) do |form| %>
  <% if basket_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>
      <ul>
        <% basket_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bg-slate-100 max-w-xl p-1 m-1 bg-white-200 rounded overflow-hidden shadow-lg shadow-slate-300 border-2 border-slate-200 hover:shadow-lime-100 hover:border-1 hover:border-slate-400">
    <%= image_tag(basket_item.image_name, class: "block object-contain h-32 box-border mb-2") %>
    <div class="px-2">
      <div class="grid grid-cols-9 gap-2 mb-2 leading-1">
        <%= form.text_field(:name, placeholder: "Name", class: "col-span-6 border-0 border-b-2 border-black text-center focus:ring-0") %>
        <%= form.collection_select :basket_id, baskets, :id, :name, {}, class: "col-span-3 border-slate-300 shadow-md shadow-slate-200 focus:ring-0 focus:border-0 focus:border-b-2" %>
      </div>
      <div class="grid grid-cols-6 gap-2 mb-2">
        <%= form.number_field :quantity, in: 1..100, step: 1, class: "col-span-1 border-slate-300 shadow-md shadow-slate-200 focus:ring-0 focus:border-0 focus:border-b-2" %>
        <%= form.select :measure, MeasureEnum.options_as_input, { prompt: "none" },  class: "col-span-2 border-slate-300 shadow-md shadow-slate-200 focus:ring-0 focus:border-0 focus:border-b-2"  %>
      </div>
      <%= form.text_area :note, placeholder: "Note", rows: 3, class: "w-full border-slate-300 shadow-md shadow-slate-200 focus:ring-0 focus:border-0 focus:border-b-2" %>
    </div>
    <div class="grid grid-cols-2 gap-2">
      <button type="button" data-action="modal#close" class="btn-outline">Abandon</button>
      <%= form.submit "Create", class: "btn bg-cyan-100", data: { modal_target: "submitButton" } %>
    </div>
  </div>
<% end %>

app/views/basket_items/_new_basket_item.html.erb
<div class="p-1 m-1 w-96 bg-white-200 rounded overflow-hidden shadow-lg shadow-slate-300 border-2 border-slate-100 hover:shadow-lime-100 hover:border-1 hover:border-lime-100">
  <div class="grid grid-cols-2 divide-x-2 divide-gray-100 items-center">
    <%= image_tag(basket_item.image_name, class: "block object-contain h-32 box-border") %>
    <div class="pl-2 box-border">
      <h2 class="text-center">
        <%= link_to "Add New", new_basket_item_path, data: { turbo_frame: "new_basket_item" }, type: "button", class: "w-full btn bg-purple-100 mr-2 px-2" %>
      </h2>
    </div>
  </div>
</div>

app/views/basket_items/create.turbo_stream.erb
<%= turbo_stream.update "new_basket_item", "" %>

app/views/basket_items/edit.html.erb
<main>
  <%= turbo_frame_tag "edit_basket_item" do %>
      <div data-modal-target="modal" data-controller="modal" class="flex items-center justify-center fixed z-40 inset-0 h-full p-6 backdrop-blur-md">
      <div data-action="keyup@document->modal#escClose click@window->modal#outsideClick">
        <%= render "form", basket_item: @basket_item, baskets: @baskets %>
      </div>
    </div>
  <% end %>
</main>

app/views/basket_items/index.html.erb
<%= turbo_stream_from "basket_item_list" %>
<div data-controller="basket-items">
  <%= turbo_frame_tag "basket_items" do %>
    <div class="m-auto max-w-7xl">
      <div class="flex flex-wrap justify-center">
        <%= form_with(url: basket_items_path, method: :get, data: { turbo_frame: "basket_items" }) do |form| %>
          <%= form.select :basket_id, options_for_select(@baskets.pluck(:name, :id), @search_basket), { include_blank: true }, { :onchange => "this.form.submit()" } %>

          <%= form.text_field :query, class: "", value: @search_value %>

          <%= form.submit 'Search', name: nil, class: "btn" %>
        <% end %>
        <%= link_to "Add New", new_basket_item_path, data: { turbo_frame: "new_basket_item" }, type: "button", class: "inline btn bg-purple-100" %>
      </div>
      <div class="flex flex-wrap justify-center" id="basket_item_list">
        <% @basket_items.each do |basket_item| %>
          <%= turbo_stream_from basket_item %>
          <%= render partial: "basket_item", locals: { basket_item: basket_item } %>
        <% end %>
      </div>
      <div class="justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  <% end %>
</div>


<%= turbo_frame_tag "new_basket_item" %>
<%= turbo_frame_tag "edit_basket_item" %>

app/views/basket_items/index.turbo_stream.erb
<%= turbo_stream.replace "basket_items" %>

app/views/basket_items/new.html.erb
<main>
  <%= turbo_frame_tag "new_basket_item" do  %>
    <div data-modal-target="modal" data-controller="modal" class="flex items-center justify-center fixed z-40 inset-0 h-full p-6 backdrop-blur-md">
      <div data-action="keyup@document->modal#escClose click@window->modal#outsideClick">
        <%= render "form", basket_item: @basket_item, baskets: @baskets  %>
      </div>
    </div>
  <% end %>
</main>

app/views/basket_items/show.html.erb
<%= turbo_stream_from @basket_item %>
<%= render @basket_item %>