config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#welcome"
  require "sidekiq/web"

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  namespace :users do
    root to: "basket_items#index"
  end

  patch 'baskets/:id/toggle_items', to: 'baskets#toggle_items', as: "toggle_items"
  resources :baskets
  resources :basket_items
end

app/views/layouts/_navbar.html.erb
<nav class="bg-slate-100 border-gray-200" data-controller="display" data-display-hidden-class="hidden">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path do  %>
      <div class="flex items-center">
        <%= image_tag("shopping-venture.png", width: 50) %>
        <span>Welcome<%= ", #{current_user&.first_name}" if current_user.present? %>!</span>
      </div>
    <% end %>

    <button class="md:hidden" data-action="click->display#toggle">
      <svg viewBox="0 0 100 80" width="2em" height="2em">
        <rect y="10" width="100" height="5"></rect>
        <rect y="30" width="100" height="5"></rect>
        <rect y="50" width="100" height="5"></rect>
      </svg>
    </button>

    <div data-display-target="section" class="hidden w-full flex flex-col items-center mt-2 md:mt-0 border-t-2 md:border-0 md:inline-flex md:flex-row md:flex-grow md:w-fit md:flex-wrap md:justify-end">
        <% if current_user %>
          <div class="flex flex-row justify-between w-4/5 md:w-fit mt-3 md:mt-0">
            <%= link_to "Baskets", baskets_path, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3" %>
            <%= link_to "Share Basket", baskets_path, data: { turbo_frame: "new_basket_item" }, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3 md:hidden" %>
          </div>
          <div class="flex flex-row justify-between w-4/5 md:w-fit mt-3 md:mt-0">
            <%= link_to "Basket Items", basket_items_path, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3" %>
            <%= link_to "Add Basket Item", new_basket_item_path, data: { turbo_frame: "new_basket_item" }, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3 md:hidden" %>
          </div>
          <div class="flex flex-row justify-between w-4/5 md:w-fit mt-3 md:mt-0">
            <%= link_to "Friends", baskets_path, data: { turbo_frame: "new_basket_item" }, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3" %>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "w-2/4 md:w-fit text-gray-500 hover:text-slate-950 text-center md:px-3" %>
          </div>
        <% else %>
          <div class="flex flex-row justify-between w-4/5 md:w-fit mt-3 md:mt-0">
            <%= link_to "Sign In", new_user_session_path, data: { turbo_frame: "sign_in_up_modal" }, class: "mx-2 bg-lime-100" %>
          </div>
          <div class="flex flex-row justify-between w-4/5 md:w-fit mt-3 md:mt-0">
            <%= link_to "Sign Up", new_user_registration_path, data: { turbo_frame: "sign_in_up_modal" }, class: "mx-2 bg-lime-100" %>
          </div>
        <% end %>
    </div>
  </div>
</nav>
<%= turbo_frame_tag "new_basket_item" %>
<%= turbo_frame_tag "sign_in_up_modal" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Basket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>